In [1]:
import pandas as pd 
import numpy as np

df=pd.read_csv('/home/ubuntu/Downloads/iris Dataset/Iris.csv')
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [3]:
mean = df['SepalWidthCm'].mean()
median = df['SepalWidthCm'].median()
mode = df['SepalWidthCm'].mode()

print("Mean of SepalWidthCm:", mean)
print("Median of SepalWidthCm:", median)
print("Mode of SepalWidthCm:", mode)

Mean of SepalWidthCm: 3.0540000000000003
Median of SepalWidthCm: 3.0
Mode of SepalWidthCm: 0    3.0
Name: SepalWidthCm, dtype: float64

In [4]:
std_A = df['SepalWidthCm'].std()
print("Standard Deviation of SepalWidthCm:", std_A)
max_A = df['SepalWidthCm'].max()
print("Maximum of SepalWidthCm:", max_A)
# Calculate minimum of column 'A'
min_A = df['SepalWidthCm'].min()
print("Minimum of SepalWidthCm:", min_A)

Standard Deviation of SepalWidthCm: 0.4335943113621737
Maximum of SepalWidthCm: 4.4
Minimum of SepalWidthCm: 2.0

In [5]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
df.groupby('Species').describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [10]:
import pandas as pd



# Group by 'species'
grouped = df.groupby('Species')


print("Mean for each species:")
print(grouped.mean())  
print("\n")

print("Median for each species:")
print(grouped.median())  
print("\n")


print("Standard Deviation for each species:")
print(grouped.std())  
print("\n")


print("Minimum for each species:")
print(grouped.min()) 
print("\n")


print("Maximum for each species:")
print(grouped.max()) 
print("\n")

print("Count of values for each species:")
print(grouped.count())

Mean for each species:
                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5          5.006         3.418          1.464
Iris-versicolor   75.5          5.936         2.770          4.260
Iris-virginica   125.5          6.588         2.974          5.552

                 PetalWidthCm
Species
Iris-setosa             0.244
Iris-versicolor         1.326
Iris-virginica          2.026


Median for each species:
                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5            5.0           3.4           1.50
Iris-versicolor   75.5            5.9           2.8           4.35
Iris-virginica   125.5            6.5           3.0           5.55

                 PetalWidthCm
Species
Iris-setosa               0.2
Iris-versicolor           1.3
Iris-virginica            2.0


Standard Deviation for each species:
                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa      14.57738       0.352490      0.381024       0.173511
Iris-versicolor  14.57738       0.516171      0.313798       0.469911
Iris-virginica   14.57738       0.635880      0.322497       0.551895

                 PetalWidthCm
Species
Iris-setosa          0.107210
Iris-versicolor      0.197753
Iris-virginica       0.274650


Minimum for each species:
                  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa        1            4.3           2.3            1.0           0.1
Iris-versicolor   51            4.9           2.0            3.0           1.0
Iris-virginica   101            4.9           2.2            4.5           1.4


Maximum for each species:
                  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa       50            5.8           4.4            1.9           0.6
Iris-versicolor  100            7.0           3.4            5.1           1.8
Iris-virginica   150            7.9           3.8            6.9           2.5


Count of values for each species:
                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [12]:
df1=df.groupby("Species")
print(df1)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x787a42306d40>

In [13]:
print(df1.groups())

TypeError: 'PrettyDict' object is not callable